#!/bin/sh

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
# zram-swap
uci set system.@system[0].zram_priority=100
# ntp server
uci -q delete system.ntp.server
uci add_list system.ntp.server="ntp1.aliyun.com"
uci add_list system.ntp.server="ntp2.aliyun.com"
uci add_list system.ntp.server="time1.cloud.tencent.com"
uci add_list system.ntp.server="time2.cloud.tencent.com"
uci add_list system.ntp.server="cn.pool.ntp.org"
uci commit system && service sysntpd reload

# uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci commit uhttpd && service uhttpd reload

# dnsmasq
uci set dhcp.lan.ra_management='1'
uci del dhcp.@dnsmasq[0].rebind_protection='1'
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
uci commit dhcp

# feed
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

ln -sf /sbin/ip /usr/bin/ip

opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
